(define (domain triangle-tire)
	(:requirements :typing :strips :non-deterministic)
	(:types location)
	(:predicates (vehicleat ?loc - location) (spare-in ?loc - location) (road ?from - location ?to - location) (not-flattire) (turnDomain) (q2 ?loc17 - location) (q3 ?loc17 - location) (q1 ?loc17 - location))
	(:action move-car
		:parameters (?from - location ?to - location)
		:precondition (and (vehicleat ?from) (road ?from ?to) (not-flattire) (turnDomain))
		:effect (and (oneof (and (vehicleat ?to) (not (vehicleat ?from))) (and (vehicleat ?to) (not (vehicleat ?from)) (not (not-flattire)))) (not (turnDomain)))
	)
	(:action changetire
		:parameters (?loc - location)
		:precondition (and (spare-in ?loc) (vehicleat ?loc) (turnDomain))
		:effect (and (not (spare-in ?loc)) (not-flattire) (not (turnDomain)))
	)
	(:action trans-0
		:parameters (?loc17 - location)
		:precondition (and (or (and (q1 ?loc17) (not (vehicleat ?loc17))) (and (q2 ?loc17) (not (vehicleat ?loc17)))) (not (turnDomain)))
		:effect (and (q2 ?loc17) (not (q3 ?loc17)) (not (q1 ?loc17)) (turnDomain))
	)
	(:action trans-1
		:parameters (?loc17 - location)
		:precondition (and (or (and (q1 ?loc17) (vehicleat ?loc17)) (and (q2 ?loc17) (vehicleat ?loc17)) (q3 ?loc17)) (not (turnDomain)))
		:effect (and (q3 ?loc17) (not (q2 ?loc17)) (not (q1 ?loc17)) (turnDomain))
	)
)